[package]
name = "num-hyperdual"
version = "0.1.0"
authors = ["Gernot Bauer <bauer@itt.uni-stuttgart.de>",
           "Philipp Rehner <rehner@itt.uni-stuttgart.de>"]
edition = "2018"

[dependencies]
num-traits = "0.2"
ndarray = { version = "0.14", optional = true }
ndarray-linalg = { version = "0.13", optional = true }

[features]
default = ["std"]
std = ["num-traits/std"]
libm = ["num-traits/libm"]
linalg = ["ndarray", "ndarray-linalg"]
openblas-system = ["ndarray-linalg/openblas-system"]
openblas-static = ["ndarray-linalg/openblas-static"]
netlib-system = ["ndarray-linalg/netlib-system"]
netlib-static = ["ndarray-linalg/netlib-static"]
intel-mkl-static = ["ndarray-linalg/intel-mkl-static"]
intel-mkl-system = ["ndarray-linalg/intel-mkl-system"]

[dev-dependencies]
criterion = "0.3"
approx = "0.3"

[[bench]]
name = "benchmark"
harness = false